elasticjob:
  reg-center:
    server-lists: zookeeper:2181
    namespace: test/op/user/elasticjob
  tracing:
    type: RDB
  jobs:
    user-common-job:
      elasticJobClass: com.kkk.op.user.web.job.UserCommonJob
      cron: 0 * * * * ?
      shardingTotalCount: 5
      overwrite: true
      disabled: false