spring:
  config:
    activate:
      on-profile: dev
elasticjob:
  reg-center:
    server-lists: localhost:2188
    namespace: dev/op/user/elasticjob
  tracing:
    type: RDB
  jobs:
    user-common-job:
      elasticJobClass: com.kkk.op.user.web.job.UserCommonJob
      cron: 0,30 * * * * ?
      shardingTotalCount: 2
      shardingItemParameters: 0=A,1=B
      overwrite: true
      disabled: false
---
spring:
  config:
    activate:
      on-profile: test
elasticjob:
  reg-center:
    server-lists: zookeeper:2181
    namespace: test/op/user/elasticjob
  tracing:
    type: RDB
  jobs:
    user-common-job:
      elasticJobClass: com.kkk.op.user.web.job.UserCommonJob
      cron: 0 * * * * ?
      shardingTotalCount: 5
      overwrite: true
      disabled: false