CREATE TABLE IF NOT EXISTS t
(
    id BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT,
    f1 VARCHAR(50)      NOT NULL,
    f2 TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    INDEX idx (f1, f2)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;